name: Build

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build1:
    runs-on: windows-2019

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create kolibri-windows
        shell: pwsh
        run: |
          mkdir build1
          cp main.sh build1/

      - name: Compress
        run: Compress-Archive -Path build1\* -DestinationPath build1.zip
        shell: pwsh

      - name: Upload ZIP build1
        uses: actions/upload-artifact@v2
        with:
          name: "build1.zip"
          path: "build1.zip"

      - name: Have output
        id: have_output
        run: echo "::set-output name=test::hello"

      - name: Get output
        run: |
          echo ${{ steps.have_output.outputs.test }}

  build2:
    runs-on: windows-2019

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create kolibri-windows
        shell: pwsh
        run: |
          mkdir build2
          cp main.sh build2/

      - name: Compress
        run: Compress-Archive -Path build2\* -DestinationPath build2.zip
        shell: pwsh

      - name: Upload ZIP build2
        uses: actions/upload-artifact@v2
        with:
          name: "build2.zip"
          path: "build2.zip"

      - name: Echo test token
        run: echo ${{ secrets.TEST_TOKEN }}
