name: Build

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build1:
    runs-on: windows-2019

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create kolibri-windows
        shell: pwsh
        run: |
          mkdir build1
          cp main.sh build1/

      - name: Compress
        run: Compress-Archive -Path build1\* -DestinationPath build1.zip
        shell: pwsh

  build2:
    runs-on: windows-2019

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create kolibri-windows
        shell: pwsh
        run: |
          mkdir build2
          cp main.sh build2/

      - name: Compress
        run: Compress-Archive -Path build2\* -DestinationPath build2.zip
        shell: pwsh
