name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  pre-build:
    runs-on: windows-2019

    steps:
      - name: Echo test token
        run: echo ${{ secrets.TEST_TOKEN }}

      - name: Echo test token again
        run: echo ${{ secrets.TEST_TOKEN }}

      - name: Create dummy files
        run: |
          rm *.appx

          echo "" > endlesskey_x64.appx
          echo "" > endlesskey_x86.appx
          echo "" > endlesskey_x64.selfsigned.appx
          echo "" > endlesskey_x86.selfsigned.appx

          ls

          echo "------------"
          Get-Childitem -Path .\ -Include *.appx -File -Recurse
          echo "------------"
          Get-Childitem *.appx -Exclude *selfsigned* -File -Recurse
          echo "------------"
          (Get-Childitem *.appx -Exclude *selfsigned* -File -Recurse) -join ", "

  build:
    needs: pre-build
    uses: ./.github/workflows/build.yml
    secrets: inherit

  publish:
    needs: build
    uses: ./.github/workflows/publish.yml
    secrets: inherit
