name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  pre-build:
    runs-on: windows-latest

    steps:
      - name: Echo test token
        run: echo ${{ secrets.TEST_TOKEN }}

  build:
    needs: pre-build
    uses: ./.github/workflows/build.yml

  publish:
    needs: build
    uses: ./.github/workflows/publish.yml
